i2s_audio:
  - id: i2s_shared
    i2s_lrclk_pin: GPIO07
    i2s_bclk_pin: GPIO08
    i2s_mclk_pin: GPIO09
    access_mode: duplex

audio_dac:
  - platform: pcm5122
    address: 0x4D
  
media_player:
  - platform: satellite1
    id: nabu_media_player
    name: Media Player
    internal: false
    sample_rate: 48000
    i2s_dout_pin: GPIO10
    bits_per_sample: 32bit
    i2s_clock_mode: external
    channel: right_left
    i2s_audio_id: i2s_shared
    volume_increment: 0.05
    volume_min: 0.4
    volume_max: 0.85
    on_mute:
      - script.execute: update_leds
    on_unmute:
      - script.execute: update_leds
    on_volume:
      - script.execute: update_leds
